### ISSUE TITLE
Do not rewrite on all possible destinations

### ISSUE THREAD

**Issue by MoKob** [mapbox/osrm-tag-rewriter#4]
Capturing from https://github.com/mapbox/directions-feedback/issues/575#issuecomment-312885363 and https://github.com/mapbox/directions-feedback/issues/575#issuecomment-312891683:

We currently rewrite `exit_to` tags into destination tags, if no `destination` tag is already present (see [here](https://github.com/mapbox/rewrite-exit-destination-signage/blob/master/rewriter.h#L93)). 

OSRM treats `destination` and `destination:ref` as a combined field, just as we did a while back with `name` and `ref`.

This results in combinations as this:
![](https://dl.dropboxusercontent.com/s/k07menlpw1t2qvz/2017-07-03%20at%2021.23.png)

It combines [this node](https://www.openstreetmap.org/node/65284716#map=19/37.71352/-122.45269) and [this way](http://www.openstreetmap.org/way/395806664) into `CA 82: SR-82` as an announcement.

We have multiple choices: handling `destination` and `destination:ref` separately in OSRM or prevent rewriting on all `destination*` flags.

For now, the simple fix would be to don't rewrite, if any destination is already present on the target way.

/cc @daniel-j-h @willwhite

**Comment by daniel-j-h** [comment]
Urgh, technically this is a limitation in osrm and our fault for combining these two tags.

Not re-writing `exit_to` tags if there is _any_ `destination*` tag on the way present seems a conservative way to handle this but if it will help with our guidance instructions I can run this out.

**Comment by willwhite** [comment]
> Urgh, technically this is a limitation in osrm and our fault for combining these two tags.

In an ideal world, how would OSRM's behavior change?

**Comment by daniel-j-h** [comment]
- Instead of strings have Json arrays in the API for properties such as `ref`, `destination`, `exits`
- Instead of combining `destination`, `destination:ref` into a single `destinations` response have dedicated properties in the response to let the user decide what to use

**Comment by daniel-j-h** [comment]
Should be fixed with https://github.com/mapbox/rewrite-exit-destination-signage/pull/5.

**Comment by willwhite** [comment]
Seems like we could do point 2 without a major API change since we'd just be adding a field.

**Comment by daniel-j-h** [comment]
This landed with https://github.com/mapbox/rewrite-exit-destination-signage/pull/5 - downstream integration is tracked elsewhere.

**Comment by daniel-j-h** [comment]
@willwhite in a perfect world yes - but passing new fields through the full osrm pipeline increases memory and disk requirements quite a bit.
