### ISSUE TITLE
Re-write exit numbers from highway junction nodes into `junction:ref` way tags

### ISSUE THREAD

**Issue by daniel-j-h** [mapbox/osrm-tag-rewriter#7]
We should re-purpose this project to handle all our tag re-writing. Maybe have a single binary with multiple re-writing passes you can enable or disable on the command line.

Specifically we need to re-write `ref` tag on the `highway=motorway_junction` node into `junction:ref` tag when unambiguously possible.

Context:
- https://github.com/Project-OSRM/osrm-backend/pull/4215
- https://github.com/Project-OSRM/osrm-backend/issues/3400#issuecomment-311326191

cc @willwhite

**Comment by 1ec5** [comment]
Note that in the case of split exits, we should rewrite the `ref:left` and `ref:right` tags as well ([example](http://www.openstreetmap.org/node/3766059022)).

Also, I’m curious what happens in the case of a `highway=motorway_junction` leading two two `highway=motorway_junction`s where one is already tagged with `junction:ref` but the other correctly omits that tag ([example](http://www.openstreetmap.org/node/1895027956)).

**Comment by 1ec5** [comment]
> Note that in the case of split exits, we should rewrite the `ref:left` and `ref:right` tags as well ([example](http://www.openstreetmap.org/node/3766059022)).

Since this tool doesn’t touch `exit_to:left` and `exit_to:right` either, we might want to copy the tags over in the data instead of doing it on the fly.
